2020-03-13 22:33:19,866 : INFO : Machine : Mission Pinball Framework Core Engine v0.53.2
2020-03-13 22:33:19,866 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': False, 'configfile': ['config.yaml'], 'mpfconfigfile': 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python36_64\\lib\\site-packages\\mpf\\mpfconfig.yaml', 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs\\2020-03-13-22-33-19-mpf-DESKTOP-BUHJ8AF.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2020-03-13 22:33:19,866 : INFO : Machine : MPF path: C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\mpf
2020-03-13 22:33:19,866 : INFO : Machine : Machine path: C:\ThompsonCodes\Pinball\MPFMachine1
2020-03-13 22:33:19,866 : INFO : Machine : Platform: win32
2020-03-13 22:33:19,866 : INFO : Machine : Python executable location: C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\python.exe
2020-03-13 22:33:19,866 : INFO : Machine : Python version: 3.6.6 (64-bit)
2020-03-13 22:33:19,866 : INFO : Machine : Machine config file #1: config.yaml
2020-03-13 22:33:19,867 : WARNING : ConfigProcessor : Config file in cache changed: C:\ThompsonCodes\Pinball\MPFMachine1\config\config.yaml
2020-03-13 22:33:19,867 : INFO : ConfigProcessor : Loading config from file C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\mpf\mpfconfig.yaml.
2020-03-13 22:33:19,924 : INFO : ConfigProcessor : Loading config: C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\mpf\mpfconfig.yaml
2020-03-13 22:33:19,930 : INFO : ConfigProcessor : Loading config from file C:\ThompsonCodes\Pinball\MPFMachine1\config\config.yaml.
2020-03-13 22:33:19,931 : ERROR : root : YAML error found in file C:\ThompsonCodes\Pinball\MPFMachine1\config\config.yaml. Line 1, Position 19: mapping values are not allowed here
  in "C:\ThompsonCodes\Pinball\MPFMachine1\config\config.yaml", line 1, column 19
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 193, in load
    config = self.process(f)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 218, in process
    return yaml.load(data_string, Loader=MpfLoader)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\ruamel\yaml\main.py", line 935, in load
    return loader._constructor.get_single_data()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\ruamel\yaml\constructor.py", line 109, in get_single_data
    node = self.composer.get_single_node()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\ruamel\yaml\composer.py", line 78, in get_single_node
    document = self.compose_document()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\ruamel\yaml\composer.py", line 101, in compose_document
    node = self.compose_node(None, None)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\ruamel\yaml\composer.py", line 138, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\ruamel\yaml\composer.py", line 211, in compose_mapping_node
    while not self.parser.check_event(MappingEndEvent):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\ruamel\yaml\parser.py", line 141, in check_event
    self.current_event = self.state()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\ruamel\yaml\parser.py", line 563, in parse_block_mapping_key
    if self.scanner.check_token(KeyToken):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\ruamel\yaml\scanner.py", line 169, in check_token
    self.fetch_more_tokens()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\ruamel\yaml\scanner.py", line 282, in fetch_more_tokens
    return self.fetch_value()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\ruamel\yaml\scanner.py", line 655, in fetch_value
    self.reader.get_mark(),
ruamel.yaml.scanner.ScannerError: mapping values are not allowed here
  in "C:\ThompsonCodes\Pinball\MPFMachine1\config\config.yaml", line 1, column 19

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\mpf\commands\game.py", line 226, in __init__
    self.machine = MachineController(mpf_path, machine_path, vars(self.args))
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\mpf\core\machine.py", line 199, in __init__
    self._load_config()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\mpf\core\machine.py", line 431, in _load_config
    store_to_cache=self.options['create_config_cache'])
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\mpf\core\config_processor.py", line 113, in load_config_files_with_cache
    ignore_unknown_sections)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\mpf\core\config_processor.py", line 169, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\mpf\core\file_manager.py", line 98, in load
    return interface.load(file, verify_version, halt_on_error)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 200, in load
    raise ValueError(msg)
ValueError: YAML error found in file C:\ThompsonCodes\Pinball\MPFMachine1\config\config.yaml. Line 1, Position 19: mapping values are not allowed here
  in "C:\ThompsonCodes\Pinball\MPFMachine1\config\config.yaml", line 1, column 19
